--USERS_URL_SEQ 생성
CREATE SEQUENCE USERS_URL_SEQ
START WITH 6
INCREMENT BY 1;

--USERS_URL_SEQ가 user_url에 저장 trigger
CREATE OR REPLACE TRIGGER USERS_URL_AI_TRG
BEFORE INSERT ON USERS
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT USERS_URL_SEQ.NEXTVAL
    INTO :NEW.user_url
    FROM DUAL;
END;
